module.exports = {
    url: 'https://testweb2.rockymountainatv.com/',
    elements: {
        keyword: '#Search > form > input.sli_searchbox_textfield',
        keywordSearch: '#MagGlassBtn',
        logIn: '.loginLink',
        logInBtn: '#loginBtn',
        email: '[name="email"]',
        password: '[name="password"]',
        closeout: '#TopNav > li:nth-child(5) > a > span.clName',
        hatSize: '#id19SelectBoxIt',
        findCloseout: '#panel3 > input',
        closeoutProduct: '#id25 > div > ul > li:nth-child(1) > div > a > span:nth-child(2)',
        addToCart: 'input[name="AddCartBtn"]',
        cartIcon: '.icon-cart',
        cart: '.acctCart',
        Checkout: '#DdCart > a:nth-child(5)',
        proceedToCheckout: '.continueBtn',
        firstName: '#firstName',
        lastName: '#lastName',
        address: '#address1',
        zip: '#zip',
        city: '#city',
        state: '#state',
        selectShipMethod: '.continueBtn',
        enterPayment: '.continueBtn',
        cashReward: '#idf2',
        giftCert: '[name="giftCertificate"]',
        giftCertBtn:'[name="applyGiftCertificateBtn"]',
        offerCode: '[name="offerCode"]',
        offerCodeBtn: '[name="applyOfferCodeBtn"]',
        cardNum: '#cardNum',
        month: '#month',
        year: '#year',
        cvv: '#cvc',
        review: '.continueBtn',
        placeOrder: '.continueBtn',
        receiptPage: '#Body > div.receipt > h1',
        selectProduct: '#Families > div:nth-child(1) > a > span:nth-child(3)', 
        casual: '#TopNav > li:nth-child(4) > a > span.clName',
        leftNav: '#LeftNavMenu > div > ul > li:nth-child(1) > a',
        color: '#idc7SelectBoxItArrowContainer', 
        size: '#idc8SelectBoxItArrowContainer',
        thankYou: '.plsPrintMsg',


    }

}